### ISSUE TITLE
Artillery activity sensor

### ISSUE THREAD

**Issue by SAOPP** [PaulAnnekov/uasiren#3]
Hi!

I think it's more a question that an bug or issue... I didn't see any time artillery sensor is turn on, even when UA app get this alarm also. Just interesting.

**Comment by PaulAnnekov** [comment]
Hi. The underlying api is api.ukrainealarm.com. That's the source of the data. To debug whether the issue is in library/integration or in api:
1. Find you region id here https://siren.pp.ua/api/v3/regions
2. When you see an artillery alarm in your app, check the region alerts `https://siren.pp.ua/api/v3/alerts/[region id]`

If you don't see artillery in list, then it's not library/integration fault.
If you do see artillery, create an issue in https://github.com/home-assistant/core repo with the following data:
1. Screenshot from Home Assistant where sensor doesn't react.
2. Region ID.
3. Reply from `https://siren.pp.ua/api/v3/alerts/[region id]`.

**Comment by SAOPP** [comment]
@PaulAnnekov Hi! Sorry for late reply.

**Sensor now:**

![image](https://user-images.githubusercontent.com/5647009/188096201-81e8cc48-49f8-43ff-a80f-3c8dc80cfc5b.png)

**Id:** `1293`

State of siren.pp.ua:

`[{"regionId":"1293","regionType":"Community","regionName":"м. Харків та Харківська територіальна громада","lastUpdate":"2022-09-02T08:10:49Z","activeAlerts":[{"regionId":"1293","regionType":"Community","type":"ARTILLERY","lastUpdate":"2022-09-02T08:10:49Z"}]}]`

**Ajax app:**

![Screenshot_20220902-111556_!](https://user-images.githubusercontent.com/5647009/188096585-ae809940-d191-49e7-91b2-d0bea0879acc.jpg)

**Comment by SAOPP** [comment]
And current states of sensors:

![image](https://user-images.githubusercontent.com/5647009/188096840-0474736f-2326-4249-ace2-08de18c3e077.png)

**Comment by SAOPP** [comment]
Oh, just re-checks this, and I think Kharkiv district it's:`[{"regionId":"124","regionType":"District","regionName":"Харківський район","lastUpdate":"2022-09-02T01:08:57Z","activeAlerts":[]}]`

But, something is wrong anyway :|

**Comment by SAOPP** [comment]
But, in integration I can't choose Kharkiv city like in Kiev, only all region and definite district.

![image](https://user-images.githubusercontent.com/5647009/188098385-da2062d9-c706-4414-b5ce-66183966deff.png)

I can't figure out where the inconsistency is :|

**Comment by SAOPP** [comment]
And again:

![Screenshot_20220902-221103_!](https://user-images.githubusercontent.com/5647009/188221844-b3b90254-b8d8-4c7a-806d-f37a07642d60.jpg)

**Comment by SAOPP** [comment]
@PaulAnnekov any suggestions?

**Comment by SAOPP** [comment]
Oh, seems da question is solved. I dunno how I can add only one distric before, but I can choose city and neiboorhood terriroty after click on Kharkiv distric, before this moment, integration added only district oy maybe I'm myself wrong. So thanks again. :+1:

**Comment by PaulAnnekov** [comment]
You're welcome.
